baseURL: http://numpy.org/
languageCode: en-us
title: NumPy
theme: hugo-fresh
disableKinds: ["taxonomyTerm"]
DefaultContentLanguage: en
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  navColor: blue
  navbarlogo:
    image: logos/numpy.svg
    link: /
  font:
    name: "Lato"
    sizes: [400,900]
  hero:
    # Main hero title
    title: NumPy
    # Hero subtitle (optional)
    subtitle: The fundamental package for scientific computing with Python
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/learn"
    # Hero image (from static/images/___)
    image: logos/numpy.svg
  # Customizable navbar. For a dropdown, add a "sublinks" list.

  section3:
    title: CASE STUDIES
    features:
    - title: First Image of a Black Hole
      text: How NumPy, together with libraries like SciPy and Matplotlib that depend on NumPy, enabled the Event Horizon Telescope to produce the first ever image of a black hole
      img: images/content_images/case_studies/blackhole.png
      alttext: First image of a black hole. It is an orange circle in a black background.
      url: /case-studies/blackhole-image
    - title: Detection of Gravitational Waves
      text: One hundred years after they were predicted by Albert Einstein, NumPy was instrumental in the first observation of gravitational waves by LIGO in 2016.
      img: images/content_images/case_studies/gravitional.png
      alttext: Two orbs orbiting each other. They are displacing gravity around them.
      url: /case-studies/gw-discov
    - title: Sports Analytics
      text: TODO!
      img: images/content_images/case_studies/sports.jpg
      alttext: Cricket ball on green field.
      url: /
  section2:
    title: KEY FEATURES
    features:
    - title: Powerful N-dimensional arrays
      text:  Fast and versatile, the NumPy vectorization, indexing and broadcasting concepts are the de-facto standards of array computing today.
    - title: Numerical computing tools
      text: NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms and more.
    - title: Interoperable
      text: NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU and sparse array libraries.
    - title: Performant
      text: The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.
    - title: Easy to use
      text: NumPy's high level syntax makes it accessible to and productive for programmers from any background or experience level.
    - title: Open source
      text: Distributed under a liberal [BSD license](https://github.com/numpy/numpy/blob/master/LICENSE.txt), NumPy is developed and maintained [publicly on GitHub](https://github.com/numpy/numpy) by a vibrant, responsive and diverse [community](/community).
  tabs:
    title: ECOSYSTEM
  section5: false

languages:
  en:
    title: NumPy
    languageName: English
    weight: 1
    contentDir: content/en
    navbar:
      - title: Install
        url: /install
      - title: Documentation
        url: https://numpy.org/doc/
      - title: Learn
        url: /learn
      - title: Array computing
        url: /arraycomputing
      - title: Community
        url: /community
      - title: About Us
        url: /about
      - title: Contribute
        url: /contribute
    footer:
      logo: numpy.svg
      socialmediatitle: ""
      socialmedia:
      - link: https://github.com/numpy/numpy
        icon: github
      - link: https://twitter.com/numpy_team
        icon: twitter
      quicklinks:
        column1:
          title: ""
          links:
            - text: Install
              link: /install
            - text: Documentation
              link: https://numpy.org/doc/
            - text: Learn
              link: /learn
            - text: Roadmap
              link: https://numpy.org/neps/roadmap.html
        column2:
          title: ""
          links:
            - text: About us
              link: /about
            - text: Community
              link: /community
            - text: Contribute
              link: /contribute
            - text: Code of conduct
              link: /code-of-conduct
        column3:
          title: ""
          links:
            - text: Get help
              link: /gethelp
            - text: Terms of use
              link: /terms
            - text: Privacy
              link: /privacy
            - text: Press kit
              link: /press-kit
  nl:
    title: NumPy
    languageName: Nederlands
    weight: 2
    contentDir: content/nl
    navbar:
      - title: Install
        url: /nl/install
      - title: Documentation
        url: https://numpy.org/doc/
      - title: Array computing
        url: /nl/arraycomputing
      - title: Case Studies
        url: /nl/case-studies/blackhole-image
      - title: Learn
        url: /nl/learn
      - title: Community
        url: /nl/community
      - title: About Us
        url: /nl/about
      - title: Contribute
        url: /nl/contribute
    footer:
      logo: numpy.svg
      socialmediatitle: ""
      socialmedia:
      - link: https://github.com/numpy/numpy
        icon: github
      - link: https://twitter.com/numpy_team
        icon: twitter
      quicklinks:
        column1:
          title: ""
          links:
            - text: Install
              link: /nl/install
            - text: Documentation
              link: https://numpy.org/doc/
            - text: Release notes
              link: /nl/release-notes
            - text: Roadmap
              link: /nl/roadmap
        column2:
          title: ""
          links:
            - text: About us
              link: /nl/about
            - text: Community
              link: /community
            - text: Contribute
              link: /nl/contribute
            - text: Code of conduct
              link:  /nl/code-of-conduct
        column3:
          title: ""
          links:
            - text: Get help
              link: /nl/gethelp
            - text: Terms of use
              link: /nl/terms
            - text: Privacy
              link: /nl/privacy
            - text: Press kit
              link: /nl/press-kit
