baseURL: http://numpy.org/
languageCode: en-us
title: NumPy
theme: hugo-fresh
disableKinds: ["taxonomyTerm"]
DefaultContentLanguage: en

params:
  navColor: blue
  navbarlogo:
    image: logos/numpy.svg
    link: /
  font:
    name: "Ubuntu"
    sizes: [400,600]
  hero:
    # Main hero title
    title: NumPy
    # Hero subtitle (optional)
    subtitle: The fundamental package for scientific computing with Python
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: logos/numpy.svg
  # Customizable navbar. For a dropdown, add a "sublinks" list.

  section3:
    title: Case Studies
    features:
    - title: First Image of Black Hole
      text:  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
      img: images/content_images/case_studies/blackhole.png
      url: /
    - title: Detection of Gravitional Waves
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
      img: images/content_images/case_studies/gravitional.png
      url: /
    - title: Sports Analytics
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
      img: images/content_images/case_studies/sports.jpg
      url: /
    - title: Self-Driving Cars
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
      img: images/content_images/case_studies/car.png
      url: /
  section2:
    title: KEY FEATURES
    features:
    - title: Powerful N-dimensional arrays
      subtitle: Fast, versatile and easy to use
      text:  Fast, versatile and easy to use, the NumPy vectorization, indexing and broadcasting concepts are the de-facto standards of array computing today.
    - title: Numerical computing tools
      text: Fundamental package for scientific computing, NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms and more.
    - title: Interoperable
      text: Works on your choice of computing platform, whether your code fits in memory and runs on a CPU or requires a GPU. NumPy supports a wide range of computing platforms and works well with all major distributed arrays and sparse arrays libraries. 
    - title: Open source
      text: Distributed under a liberal [BSD license](https://github.com/numpy/numpy/blob/master/LICENSE.txt), NumPy is developed and maintained publicly on GitHub by a vibrant, responsive and diverse community.
  tabs:
    title: Ecosystem
    subtitle:
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section5: false

languages:
  en:
    title: NumPy
    languageName: English
    weight: 1
    contentDir: content/en
    navbar:
      - title: Install
        url: /install
      - title: Documentation
        url: /doc
      - title: Learn
        url: /learn
      - title: Array computing
        url: /arraycomputing
      - title: Community
        url: /community
      - title: About Us
        url: /about
      - title: Contribute
        url: /contribute
    footer:
      logo: numpy.svg
      socialmediatitle: ""
      socialmedia:
      - link: https://github.com/numpy/numpy
        icon: github
      - link: https://twitter.com/numpy_team
        icon: twitter
      quicklinks:
        column1:
          title: ""
          links:
            - text: Install
              link: /install
            - text: Documentation
              link: /docs
            - text: Learn
              link: /learn
            - text: Roadmap
              link: https://numpy.org/neps/roadmap.html
        column2:
          title: ""
          links:
            - text: About us
              link: /about
            - text: Community
              link: /community
            - text: Code of conduct
              link: /code-of-conduct
            - text: Get help
              link: /help
            - text: Contribute
              link: /contribute
        column3:
          title: ""
          links:
            - text: Terms of use
              link: /terms
            - text: Privacy
              link: /privacy
            - text: Trademarks
              link: /trademarks
            - text: Press kit
              link: /press-kit
  nl:
    title: NumPy
    languageName: Dutch
    weight: 2
    contentDir: content/nl
    navbar:
      - title: Install
        url: /nl/install
      - title: Documentation
        url: /nl/doc
      - title: Array computing
        url: /nl/arraycomputing
      - title: Learn
        url: /nl/learn
      - title: Community
        url: /nl/community
      - title: About Us
        url: /nl/about
      - title: Contribute
        url: /nl/contribute
    footer:
      logo: numpy.svg
      socialmediatitle: ""
      socialmedia:
      - link: https://github.com/numpy/numpy
        icon: github
      - link: https://twitter.com/numpy_team
        icon: twitter
      quicklinks:
        column1:
          title: ""
          links:
            - text: Install
              link: /nl/install
            - text: Documentation
              link: /nl/docs
            - text: Release notes
              link: /nl/release-notes
            - text: Roadmap
              link: /nl/roadmap
        column2:
          title: ""
          links:
            - text: About us
              link: /nl/about
            - text: Code of conduct
              link: /nl/code-of-conduct
            - text: Get help
              link: /nl/help
            - text: Contribute
              link: /nl/contribute
        column3:
          title: ""
          links:
            - text: Terms of use
              link: /nl/terms
            - text: Privacy
              link: /nl/privacy
            - text: Trademarks
              link: /nl/trademarks
            - text: Press kit
              link: /nl/press-kit
  hi:
    title: NumPy
    languageName: Hindi
    weight: 3
    contentDir: content/hi
    navbar:
      - title: Install
        url: /hi/install
      - title: Documentation
        url: /hi/doc
      - title: Array computing
        url: /hi/arraycomputing
      - title: Learn
        url: /hi/learn
      - title: Community
        url: /hi/community
      - title: About Us
        url: /hi/about
      - title: Contribute
        url: /hi/contribute
    footer:
      logo: numpy.svg
      socialmediatitle: ""
      socialmedia:
      - link: https://github.com/numpy/numpy
        icon: github
      - link: https://twitter.com/numpy_team
        icon: twitter
      quicklinks:
        column1:
          title: ""
          links:
            - text: Install
              link: /hi/install
            - text: Documentation
              link: /hi/docs
            - text: Release notes
              link: /hi/release-notes
            - text: Roadmap
              link: /hi/roadmap
        column2:
          title: ""
          links:
            - text: About us
              link: /hi/about
            - text: Code of conduct
              link: /hi/code-of-conduct
            - text: Get help
              link: /hi/help
            - text: Contribute
              link: /hi/contribute
        column3:
          title: ""
          links:
            - text: Terms of use
              link: /hi/terms
            - text: Privacy
              link: /hi/privacy
            - text: Trademarks
              link: /hi/trademarks
            - text: Press kit
              link: /hi/press-kit
