baseURL: http://numpy.org/
languageCode: en-us
title: NumPy
theme: hugo-fresh
disableKinds: ["taxonomyTerm"]
DefaultContentLanguage: en

params:
  navColor: blue
  navbarlogo:
    image: logos/numpy.svg
    link: /
  font:
    name: "Ubuntu"
    sizes: [400,600]
  hero:
    # Main hero title
    title: NumPy
    # Hero subtitle (optional)
    subtitle: The fundamental package for scientific computing and data science with Python
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: logos/numpy.svg
  # Customizable navbar. For a dropdown, add a "sublinks" list.

  section2:
    title: In a Nutshell
    subtitle:
    features:
    - title: Powerful N-dimensional arrays
      icon: cartesian
      text: NumPy arrays are easy to use, versatile and fast. The NumPy vectorization, indexing and broadcasting concepts have become a standard way of thinking about array computing.
    - title: Numerical computing tools
      icon: chip
      text: Mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.
    - title: Interoperable
      icon: computer
      text: NumPy supports a wide range of computing platforms. If your data fits in memory and your code runs on a CPU, NumPy is for you! And if you need GPU, distributed or sparse arrays, NumPy works well with all the major libraries that provide that.
    - title: Open source
      icon: web-programming
      text: NumPy is free for everyone to use, publicly developed on GitHub by a diverse community, and distributed under a liberal BSD license.
  tabs:
    title: Ecosystem
    subtitle:
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: numpy.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/numpy
      # Icons are from Font Awesome
      icon: github
    - link: https://twitter.com/lucperkins
      icon: twitter
    # TODO: not yet organized well (footer links need to differ from header
    # links)
    bulmalogo: false
    quicklinks:
      column1:
        title: "Pages"
        links:
        - text: About us
          link: /about
        - text: Community
          link: /community
        - text: Install
          link: /install
        - text: Learning
          link: /learning
        - text: Documentation
          link: /doc
        - text: Array computing
          link: /arraycomputing
      column2:
        title: "Docs"
        links:
        - text: Getting started
          link: /
        - text: User guide
          link: /
        - text: Reference guide
          link: /

languages:
  en:
    title: NumPy
    languageName: English
    weight: 1
    contentDir: content/en
    navbar:
      - title: Install
        url: /install
      - title: Documentation
        url: /doc
      - title: Array computing
        url: /arraycomputing
      - title: Learn
        url: /learn
      - title: Community
        url: /community
      - title: About Us
        url: /aboutus
      - title: Contribute
        url: /contribute
  nl:
    title: NumPy
    languageName: Dutch
    weight: 2
    contentDir: content/nl
    navbar:
      - title: Install
        url: /nl/install
      - title: Documentation
        url: /nl/doc
      - title: Array computing
        url: /nl/arraycomputing
      - title: Learn
        url: /nl/learn
      - title: Community
        url: /nl/community
      - title: About Us
        url: /nl/aboutus
      - title: Contribute
        url: /nl/contribute
  hi:
    title: NumPy
    languageName: Hindi
    weight: 3
    contentDir: content/hi
    navbar:
      - title: Install
        url: /hi/install
      - title: Documentation
        url: /hi/doc
      - title: Array computing
        url: /hi/arraycomputing
      - title: Learn
        url: /hi/learn
      - title: Community
        url: /hi/community
      - title: About Us
        url: /hi/aboutus
      - title: Contribute
        url: /hi/contribute
