# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build.environment]
  PYTHON_VERSION = "3.8"
  # Same Hugo version as in .github/workflows/gh-pages.yml
  HUGO_VERSION = "0.98.0"

# Here is another way to define context specific environment variables.
[context.deploy-preview.environment]
  NUMPYORG_WITH_TRANSLATIONS = "1"

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    todoPatterns = [" public/pt/user-surveys", " public/ja/user-surveys"]


[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.4
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.7
    pwa = 0.2

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
