# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build.environment]
  PYTHON_VERSION = "3.13"
  DART_SASS_VERSION = "1.83.4"
  HUGO_VERSION = "0.152.2"
  DART_SASS_URL = "https://github.com/sass/dart-sass/releases/download/"

[build]
  base = "/"
  publish = "public"
  command = """\
    export DART_SASS_TARBALL="dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
    curl -LJO ${DART_SASS_URL}/${DART_SASS_VERSION}/${DART_SASS_TARBALL} && \
    tar -xf ${DART_SASS_TARBALL} && \
    rm ${DART_SASS_TARBALL} && \
    export PATH=/opt/build/repo/dart-sass:$PATH && \
    pip install pyyaml && \
    make html \
    """

# Here is another way to define context specific environment variables.
[context.deploy-preview.environment]
  NUMPYORG_WITH_TRANSLATIONS = "1"

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    todoPatterns = [" public/pt/user-surveys", " public/ja/user-surveys"]
    skipPatterns = ["https://fonts.gstatic.com", "https://fonts.googleapis.com"]
