[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/43481325?u=8c0c0adbf3f2efd2cce72951d3554064c7bbfce3&v=4"
    alt="Avatar of Inessa Pawson"
>}}
Inessa Pawson'''
link = 'https://github.com/InessaPawson'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/123428?v=4"
    alt="Avatar of Jarrod Millman"
>}}
Jarrod Millman'''
link = 'https://github.com/jarrodmillman'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/3891660?u=5de0ba1f1adad6f041f6dde1affef5d05bbed80a&v=4"
    alt="Avatar of Joe LaChance"
>}}
Joe LaChance'''
link = 'https://github.com/joelachance'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/46167686?u=b5ca05a767012822d06b8bc16e3cd5ca0d1cafe9&v=4"
    alt="Avatar of Mars Lee"
>}}
Mars Lee'''
link = 'https://github.com/MarsBarLee'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/98330?u=22a023f8d191ba200ab13d476c83860d015cc9fe&v=4"
    alt="Avatar of Ralf Gommers"
>}}
Ralf Gommers'''
link = 'https://github.com/rgommers'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/5890484?u=feb15a24e010a434ded00e41d8bd030a2cc31bdb&v=4"
    alt="Avatar of shalz"
>}}
shalz'''
link = 'https://github.com/shaloo'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/5774448?u=af1d8beea7d3c37d064e0dcb42d96c41e1318934&v=4"
    alt="Avatar of Shekhar Prasad Rajak"
>}}
Shekhar Prasad Rajak'''
link = 'https://github.com/Shekharrajak'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/45071?u=c779b5e06448fbc638bc987cdfe305c7f9a7175e&v=4"
    alt="Avatar of Stefan van der Walt"
>}}
Stefan van der Walt'''
link = 'https://github.com/stefanv'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/1953382?u=5df9d41ad2a6d526e7daeec06225274905e7e660&v=4"
    alt="Avatar of Albert Steppi"
>}}
Albert Steppi'''
link = 'https://github.com/steppi'
