# FOR TRANSLATORS: this is a YAML file, with lines being of the form:
#
#   key: value
#
# Please translate the `value`s, not the `key`s!
# Comments (starting with `#`) and `url:` or `link:` lines also do not
# need to be translated. `title:` and `text:` lines do need translation.
#
languageName: 日本語 (Japanese)
params:
  description: NumPyが広く利用される理由 強力な多次元配列、数値計算ツール群、相互運用性、高いパフォーマンス、オープンソース
  navbarlogo:
    image: logo.svg
    link: /ja/

  hero:
    title: NumPy
    subtitle: Pythonによる科学技術計算の基礎パッケージ
    buttontext: 使い始める
    buttonlink: "/ja/install"
    image: logo.svg

  news:
    title: NumPy v1.20.0
    content: 型アノテーションサポート - 複数のプラットフォームにおけるSIMDを利用したパフォーマンス改善
    url: /ja/news

  shell:
    title: placeholder # do not translate

    intro:
    - title: Try NumPy
      text: Use the interactive shell to try NumPy in the browser

    docslink: Don't forget to check out the <a href="https://numpy.org/doc/stable" target="_blank">docs</a>.

  casestudies:
    title: ケーススタディ
    features:
    - title: 世界初のブラックホール画像
      text: NumPyはどのように、SciPyやMatplotlibなどのNumPyに依存するライブラリとともに、イベントホライズンテレスコープによる世界初のブラックホール画像の作成を可能にしたのでしょうか。
      img: /images/content_images/case_studies/blackhole.png
      alttext: 世界初のブラックホール画像。黒い背景にオレンジ色の円で描かれています。
      url: /ja/case-studies/blackhole-image
    - title: 重力波の検知
      text: 1916年、アルバート・アインシュタインは重力波を予言しました。100年後、LIGOの研究者たちはNumPyを使ってその存在を確認しました。
      img: /images/content_images/case_studies/gravitional.png
      alttext: 2つのオーブがお互いに周回し、周りの重力を変位させています。
      url: /ja/case-studies/gw-discov
    - title: スポーツ分析
      text: クリケット分析は、統計的モデリングと予測分析によって選手やチームのパフォーマンスを向上させることで、クリケットの試合を変えようとしています。多くの分析が、NumPyにより可能になりました。
      img: /images/content_images/case_studies/sports.jpg
      alttext: 緑のフィールド上にあるクリケットボール。
      url: /ja/case-studies/cricket-analytics
    - title: 深層学習による姿勢推定
      text: DeepLabCutはNumPyを利用し、種族・時間スケールによらない運動制御の理解へ向け、動物の行動観察を含む科学技術研究を加速しています。
      img: /images/content_images/case_studies/deeplabcut.png
      alttext:  チータの姿勢推定
      url: /ja/case-studies/deeplabcut-dnn

  keyfeatures:
    features:
    - title: 強力な多次元配列
      text:  NumPyの高速で多機能なベクトル化計算、インデックス処理、ブロードキャスティングのコンセプトは、今日の配列計算のデファクト・スタンダードです。
    - title: 数値計算ツール群
      text: NumPyは、様々な数学関数、乱数生成器、線形代数ルーチン、フーリエ変換などを提供しています。
    - title: 相互運用性
      text: NumPyは、幅広いハードウェアとコンピューティング・プラットフォームをサポートしており、分散処理、GPU、疎行列ライブラリにも対応しています。
    - title: 高パフォーマンス
      text: NumPyの中核は最適化されたC言語のコードです。Pythonの柔軟性を、コンパイルされたコードの高速さとともに享受できます。
    - title: 使いやすさ
      text: NumPyの高水準なシンタックスは、どんなバックグラウンドや経験値のプログラマーでも利用でき、生産性を高めることができます。
    - title: オープンソース
      text: 寛容な[BSDライセンス](https://github.com/numpy/numpy/blob/main/LICENSE.txt)で公開されています。NumPyは活発で、互いを尊重し、多様性を認め合う[コミュニティ](/ja/community)によって、 [GitHub](https://github.com/numpy/numpy)上でオープンに開発されています.

  tabs:
    title: エコシステム
  section5: false

navbar:
  - title: インストール
    url: /ja/install
  - title: ドキュメント
    url: https://numpy.org/doc/stable
  - title: 学び方
    url: /ja/learn
  - title: コミュニティ
    url: /ja/community
  - title: 私達について
    url: /ja/about
  - title: NumPyに貢献する
    url: /ja/contribute

footer:
  logo: logo.svg
  socialmediatitle: ""
  socialmedia:
  - link: https://github.com/numpy/numpy
    icon: github
  - link: https://www.youtube.com/channel/UCguIL9NZ7ybWK5WQ53qbHng
    icon: youtube
  - link: https://twitter.com/numpy_team
    icon: twitter
  quicklinks:
    column1:
      title: ""
      links:
        - text: インストール
          link: /ja/install
        - text: ドキュメント
          link: https://numpy.org/doc/stable
        - text: 学び方
          link: /ja/learn
        - text: 引用する
          link: /ja/citing-numpy
        - text: ロードマップ
          link: https://numpy.org/neps/roadmap.html
    column2:
      links:
        - text: 私達について
          link: /ja/about
        - text: コミュニティ
          link: /ja/community
        - text: User surveys
          link: /ja/user-surveys
        - text: NumPyに貢献する
          link: /ja/contribute
        - text: 行動規範
          link: /ja/code-of-conduct
    column3:
      links:
        - text: サポートを得る方法
          link: /ja/gethelp
        - text: 利用規約
          link: /ja/terms
        - text: プライバシーポリシー
          link: /ja/privacy
        - text: プレス用資料
          link: /ja/press-kit
