languageName: Inglés
params:
  description: '¿Por qué NumPy? Potentes matrices n-dimensionales. Herramientas de cálculo numérico. Interoperable. Rendimiento. Código abierto.'
  navbarlogo:
    image: logo.svg
    link: /
  hero:
    #Main hero title
    title: NumPy
    #Hero subtitle (optional)
    subtitle: El paquete fundamental para la computación científica con Python
    #Button text
    buttontext: "Última versión: NumPy 1.25. Ver todas las versiones"
    #Where the main hero button links to
    buttonlink: "/news/#releases"
    #Hero image (from static/images/___)
    image: logo.svg
  shell:
    title: marcador
    intro:
      - 
        title: Prueba NumPy
        text: Utilice el terminal interactivo para probar NumPy en el navegador
    docslink: No olvides echarle un ojo a la <a href="https://numpy.org/doc/stable" target="_blank">documentación</a>.
  casestudies:
    title: CASOS DE ESTUDIO
    features:
      - 
        title: Primera imagen de un Agujero Negro
        text: Cómo NumPy, junto con bibliotecas como SciPy y Matplotlib que dependen de NumPy, permitió al Event Horizon Telescope producir la primera imagen de un agujero negro
        img: /images/content_images/case_studies/blackhole.png
        alttext: Primera imagen de un agujero negro. Es un círculo anaranjado con fondo negro.
        url: /case-studies/blackhole-image
      - 
        title: Detección de Ondas Gravitacionales
        text: En 1916 Albert Einstein predijo las ondas gravitacionales; 100 años después se confirmó su existencia por científicos del LIGO, utilizando NumPy.
        img: /images/content_images/case_studies/gravitional.png
        alttext: Dos cuerpos orbitándose mutuamente. Estos desplazan la gravedad a su alrededor.
        url: /case-studies/gw-discov
      - 
        title: Analíticas Deportivas
        text: El uso de Analíticas está cambiando al Cricket, al mejorar el rendimiento de los jugadores y equipos, mediante modelos estadísticos y análisis predictivos. NumPy permite realizar muchos de estos análisis.
        img: /images/content_images/case_studies/sports.jpg
        alttext: Bola de Cricket sobre un campo verde.
        url: /case-studies/cricket-analytics
      - 
        title: Estimación de la pose mediante aprendizaje profundo
        text: DeepLabCut utiliza NumPy para acelerar estudios científicos que implican la observación del comportamiento animal para una mejor comprensión del control motriz, a través de especies y escalas de tiempo.
        img: /images/content_images/case_studies/deeplabcut.png
        alttext: Análisis de la pose de un Guepardo
        url: /case-studies/deeplabcut-dnn
  keyfeatures:
    features:
      - 
        title: Matrices N-dimensionales Poderosas
        text: Rápidos y versátiles, los conceptos de vectorización, indexación y retransmisión de NumPy son los estándares de facto de la computación de matrices en la actualidad.
      - 
        title: Herramientas de Cómputo Numérico
        text: NumPy ofrece funciones matemáticas integrales, generadores de números aleatorios, rutinas de álgebra lineal, transformadas de Fourier y mucho más.
      - 
        title: Código abierto
        text: Distribuida bajo la licencia liberal [BSD](https://github.com/numpy/numpy/blob/main/LICENSE.txt), NumPy es desarrollado y mantenido [públicamente en GitHub](https://github.com/numpy/numpy) por una [comunidad](/community) vibrante, responsable y diversa.
      - 
        title: Interoperable
        text: NumPy es compatible con una amplia gama de plataformas informáticas y de hardware, y funciona bien con bibliotecas distribuidas, de GPU y de matrices dispersas.
      - 
        title: Rendimiento
        text: El núcleo de NumPy es código C bien optimizado. Disfrute de la flexibilidad de Python con la velocidad del código compilado.
      - 
        title: Fácil de usar
        text: La sintaxis de alto nivel de NumPy lo hace accesible y productivo para programadores de cualquier formación o nivel de experiencia.
  tabs:
    title: ECOSISTEMA
  section5: false
  navbar:
    - 
      title: Instalar
      url: /install
    - 
      title: Documentación
      url: https://numpy.org/doc/stable
    - 
      title: Aprende
      url: /learn
    - 
      title: Comunidad
      url: /community
    - 
      title: Acerca de nosotros
      url: /about
    - 
      title: Noticias
      url: /news
    - 
      title: Contribuye
      url: /contribute
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - 
        link: https://github.com/numpy/numpy
        icon: github
      - 
        link: https://www.youtube.com/channel/UCguIL9NZ7ybWK5WQ53qbHng
        icon: youtube
      - 
        link: https://twitter.com/numpy_team
        icon: twitter
    quicklinks:
      column1:
        title: ""
        links:
          - 
            text: Instalar
            link: /install
          - 
            text: Documentación
            link: https://numpy.org/doc/stable
          - 
            text: Aprende
            link: /learn
          - 
            text: Citando a NumPy
            link: /citing-numpy
          - 
            text: Mapa de ruta
            link: https://numpy.org/neps/roadmap.html
      column2:
        links:
          - 
            text: Acerca de nosotros
            link: /about
          - 
            text: Comunidad
            link: /community
          - 
            text: Encuestas a usuarios
            link: /user-surveys
          - 
            text: Contribuye
            link: /contribute
          - 
            text: Código de Conducta
            link: /code-of-conduct
      column3:
        links:
          - 
            text: Buscar ayuda
            link: /gethelp
          - 
            text: Términos de uso
            link: /terms
          - 
            text: Confidencialidad
            link: /privacy
          - 
            text: Kit de prensa
            link: /press-kit
