[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/3949932?u=aacac68df60d2cf64c17c7e5aa17adf8b738aa7b&v=4"
    alt="Avatar of Melissa Weber Mendonça"
>}}
Melissa Weber Mendonça'''
link = 'https://github.com/melissawm'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://raw.githubusercontent.com/numpy/numpy.org/refs/heads/main/static/images/logo.svg"
    alt="Avatar of Juan Pablo Duque"
>}}
Juan Pablo Duque (@juanpabloduqueo)'''
link = 'https://scientific-python.crowdin.com'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://raw.githubusercontent.com/numpy/numpy.org/refs/heads/main/static/images/logo.svg"
    alt="Avatar of Yeimi Pena"
>}}
Yeimi Pena (@yeimiyaz)'''
link = 'https://www.linkedin.com/in/yeimipena/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/3813847?v=4"
    alt="Avatar of Atsushi Sakai"
>}}
Atsushi Sakai (@AtsushiSakai)'''
link = 'https://github.com/AtsushiSakai'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://raw.githubusercontent.com/numpy/numpy.org/refs/heads/main/static/images/logo.svg"
    alt="Avatar of Getúlio Silva"
>}}
Getúlio Silva (@getuliosilva)'''
link = 'https://scientific-python.crowdin.com'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://raw.githubusercontent.com/numpy/numpy.org/refs/heads/main/static/images/logo.svg"
    alt="Oriol Abril-Pla"
>}}
Oriol Abril-Pla (@OriolAbril)'''
link = 'https://scientific-python.crowdin.com'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://raw.githubusercontent.com/numpy/numpy.org/refs/heads/main/static/images/logo.svg"
    alt="Avatar of @julio"
>}}
@julio'''
link = 'https://scientific-python.crowdin.com'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://raw.githubusercontent.com/numpy/numpy.org/refs/heads/main/static/images/logo.svg"
    alt="Avatar of Ali Faraji"
>}}
Ali Faraji (@ali)'''
link = 'https://scientific-python.crowdin.com'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://raw.githubusercontent.com/numpy/numpy.org/refs/heads/main/static/images/logo.svg"
    alt="Avatar of Saeed Foroutan"
>}}
Saeed Foroutan (@SaeedForoutan)'''
link = 'https://scientific-python.crowdin.com'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://raw.githubusercontent.com/numpy/numpy.org/refs/heads/main/static/images/logo.svg"
    alt="Avatar of @pyjavo"
>}}
@pyjavo'''
link = 'https://scientific-python.crowdin.com'
